spring:
  application:
    name: SpringMVCModuleJsonView
  datasource:
    url: jdbc:postgresql://postgres-service:5432/db-name
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
